version: '3'
services:
    db:
      user: root
      container_name: crm_edc_db
      image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
      ports:
        - 1433:1433
      volumes:
        - ./data:/var/opt/mssql/data
      tty: true
      stdin_open: true
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password12!
        - MSSQL_PID=Developer
